// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://faghzdmlkbvvfkoopvqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhZ2h6ZG1sa2J2dmZrb29wdnFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0OTg3MTUsImV4cCI6MjA3MDA3NDcxNX0.LHC-GT03I2vc4wZu8blkEMNUCB7pHhVn2fQqztqdjek";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});